<div dir="rtl" align="center">
<font face="B Yekan" size=4>
    <font face="IranNastaliq" size=5>
      به نام خدا
    </font>
    <br>
    <font size=3>
    دانشکده صنایع دانشگاه صنعتی شریف
    </font>
    <br>
    <font color=blue size=5>
      یادگیری ماشین
    </font>
        <br>
    <font color=blue size=5>
دکتر مهدی شریف زاده      
    </font>
    <br>
    <hr/>
    <font color= blue size=3>
    رضا الوندی
        </font>
    <hr/>
        <font color=red size=6>
یادآوری کتابخانه numpy  
  </font>
    <hr/>
    <br>
    مثال های جلسه سوم
    <hr>


# Numpy Introduction
## numpy arrays

In [91]:
import numpy as np
arr = np.array([1,3,4,5,6])
arr

array([1, 3, 4, 5, 6])

In [8]:
arr.shape

(5,)

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr = np.array([1,'st','er',3])
arr.dtype

dtype('<U11')

In [5]:
np.sum(arr)

TypeError: cannot perform reduce with flexible type

### Creating arrays

In [11]:
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])
arr.shape

(3, 3)

In [12]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [13]:
arr = np.zeros((2,4))
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [14]:
arr = np.ones((2,4))
arr

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [15]:
arr = np.identity(3)
arr

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [16]:
arr = np.random.randn(3,4)
arr

array([[ 0.11069212, -1.3712359 , -0.35438971,  0.03397169],
       [ 0.35755146, -1.15864674,  0.49294546, -0.59452261],
       [ 0.85139437,  0.75329689, -0.57315488, -0.02419983]])

In [17]:
from io import BytesIO
b = BytesIO(b"2,23,33\n32,42,63.4\n35,77,12")
arr = np.genfromtxt(b, delimiter=",")
arr

array([[  2. ,  23. ,  33. ],
       [ 32. ,  42. ,  63.4],
       [ 35. ,  77. ,  12. ]])

### Accessing array elements
#### Simple indexing

In [18]:
arr[1]

array([ 32. ,  42. ,  63.4])

In [19]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [20]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
arr = np.arange(10)
arr[5:]


array([5, 6, 7, 8, 9])

In [22]:
arr[5:8]

array([5, 6, 7])

In [23]:
arr[:-5]

array([0, 1, 2, 3, 4])

In [24]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
arr[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
arr[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [28]:
arr[...,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

#### Advanced Indexing

In [29]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
arr[[0,1,2],[1,0,0]]

array([1, 3, 6])

##### Boolean Indexing

In [31]:
cities = np.array(["delhi","banglaore","mumbai","chennai","bhopal"])
city_data = np.random.randn(5,3)
city_data

array([[-0.04941315, -0.41476745, -0.60236098],
       [-1.75033842,  0.62559942, -0.58148095],
       [ 0.43502897, -0.06588454, -0.40865494],
       [-0.53978394, -0.7317352 , -0.66959325],
       [ 0.45550659, -0.53018559, -0.2241479 ]])

In [32]:
city_data[cities =="delhi"]

array([[-0.04941315, -0.41476745, -0.60236098]])

In [33]:
city_data[city_data >0]

array([ 0.62559942,  0.43502897,  0.45550659])

In [34]:
city_data[city_data >0] = 0
city_data


array([[-0.04941315, -0.41476745, -0.60236098],
       [-1.75033842,  0.        , -0.58148095],
       [ 0.        , -0.06588454, -0.40865494],
       [-0.53978394, -0.7317352 , -0.66959325],
       [ 0.        , -0.53018559, -0.2241479 ]])

#### Operations on arrays

In [35]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [38]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(5).reshape(5,1)
arr2 + arr1


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [39]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [40]:
arr2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [41]:
arr1 = np.random.randn(5,3)
arr1

array([[-0.92631238, -0.75087049,  0.38818842],
       [ 1.34359452, -0.68896739, -0.58429706],
       [ 1.06638747, -0.40104143,  0.99089011],
       [ 0.26232893,  1.4349162 , -0.97503394],
       [ 0.35716111,  0.20198017,  0.08151897]])

In [42]:
np.modf(arr1)

(array([[-0.92631238, -0.75087049,  0.38818842],
        [ 0.34359452, -0.68896739, -0.58429706],
        [ 0.06638747, -0.40104143,  0.99089011],
        [ 0.26232893,  0.4349162 , -0.97503394],
        [ 0.35716111,  0.20198017,  0.08151897]]), array([[-0., -0.,  0.],
        [ 1., -0., -0.],
        [ 1., -0.,  0.],
        [ 0.,  1., -0.],
        [ 0.,  0.,  0.]]))

#### Linear algebra using numpy

In [43]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[1,2,3]])
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [44]:
A = np.arange(15).reshape(3,5)
A.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [45]:
np.linalg.svd(A)

(array([[-0.15425367,  0.89974393,  0.40824829],
        [-0.50248417,  0.28432901, -0.81649658],
        [-0.85071468, -0.3310859 ,  0.40824829]]),
 array([  3.17420265e+01,   2.72832424e+00,   4.58204637e-16]),
 array([[-0.34716018, -0.39465093, -0.44214167, -0.48963242, -0.53712316],
        [-0.69244481, -0.37980343, -0.06716206,  0.24547932,  0.55812069],
        [ 0.33717486, -0.77044776,  0.28661392,  0.38941603, -0.24275704],
        [-0.36583339,  0.32092943, -0.08854543,  0.67763613, -0.54418674],
        [-0.39048565,  0.05843412,  0.8426222 , -0.29860414, -0.21196653]]))

In [46]:
a = np.array([[7,5,-3], [3,-5,2],[5,3,-7]])
b = np.array([16,-8,0])
x = np.linalg.solve(a, b)
x

array([ 1.,  3.,  2.])

In [47]:
np.allclose(np.dot(a, x), b)

True